### ISSUE TITLE
OpenVolumeMesh not accessible

### ISSUE THREAD

**Issue by chiefenne** [cgg-bern/AlgoHex#1]
the site for Openvolumemesh seems to be down
also MOSEK could not be found

**Comment by sebmestrallet** [comment]
Hello, I too found an issue with the URL for OpenVolumeMesh.
```txt
[OpenVolumeMesh](www.openvolumemesh.org)
```
should be instead
```txt
[OpenVolumeMesh](https://www.openvolumemesh.org)
```
in the README. https://www.openvolumemesh.org works and redirect to https://www.graphics.rwth-aachen.de/software/openvolumemesh/. 

As for MOSEK, I don't know. I don't have it installed and successfully compiled AlgoHex.

**Comment by HengLiuNotAvailable** [comment]
Hi, thanks for reporting the URL issue. MOSEK is not a necessary dependency for the current version of AlgoHex.
