### ISSUE TITLE
Build error with CoMISo

### ISSUE THREAD

**Issue by rl00100** [cgg-bern/AlgoHex#11]
Hi, 

I am trying to compile AlgoHex in Ubuntu 18.04, but the build fails when compiling "external/CoMISo/CMakeFiles/CoMISo.dir/NSolver/NewtonSolver.cc.o". I'm not sure if i have missed a dependency, or some other mistake i have made is causing the issue. 

I have attached the logs for the cmake config, and when i attempt to build. 
[Build_Log.txt](https://github.com/cgg-bern/AlgoHex/files/13945014/Build_Log.txt)
[Cmake_prep.txt](https://github.com/cgg-bern/AlgoHex/files/13945015/Cmake_prep.txt)

Cheers, 

Rob

**Comment by mheistermann** [comment]
Hi Rob!
Thanks for reporting the issue, it's not your mistake, but ours. We're pulling in the `master` branch of Eigen, which currently has some breakage. I'll fix it later today by fixing the versions of dependencies to known-good ones.

**Comment by mheistermann** [comment]
Please try with current `main` (and possibly a fresh build folder), I used the opportunity to do a bigger overhaul of the dependency handling CMake code.

If you still run into problems, please re-open this issue (or open a new one if you encounter an unrelated problem).

**Comment by rl00100** [comment]
I think your Eigen branch is private, i keep getting permission issues when i run the new main.

**Comment by mheistermann** [comment]
Oops! Sorry, fixed that.

(FYI: I had to link to my branch as [the associated merge request](https://gitlab.com/libeigen/eigen/-/merge_requests/1451) was not accepted yet.)

Please try again :)

**Comment by rl00100** [comment]
Thanks,built without any issue :)

To use with my solver i will have to convert from the OVM format, I have been trying to use the meshio fork you have listed in other issues but the commands do not work.

**Comment by mheistermann** [comment]
Great to hear! Sorry for the inconvenience with the OVM file format. We'll add other output formats in the future, but I can't give a timeline for that. Feel free to open a fresh issue for conversion problems - the forked meshio should work for ascii `.ovm` files (not for binary `.ovmb` files), with the caveat of not converting additional data (OVM properties) that are used for feature information.
