### ISSUE TITLE
visualization of output hex mesh

### ISSUE THREAD

**Issue by MaguRaam** [cgg-bern/AlgoHex#20]
Hi, how can I visualize the output hexahedral mesh? They are in .ovm format. Or is there any tool to convert it to vtk?

**Comment by otaolafranc** [comment]
hello, you have openFlipper check this comment: https://github.com/cgg-bern/AlgoHex/issues/19#issuecomment-2172870449
also from memory, you have the hexalab.net that can open ovm, but I am not 100% sure.

**Comment by MaguRaam** [comment]
Hi, thank you. I will use openFlipper. Hexalab.net does not support the ovm format.
