### ISSUE TITLE
 Gurobi dependency

### ISSUE THREAD

**Issue by chiefenne** [cgg-bern/AlgoHex#6]
Will there be some activities to get rid of the Gurobi dpendency, as this is a real hurdle?
I think of toolboxes like Casadi, etc., which are free.

Best regards,
Andreas

**Comment by mheistermann** [comment]
QGP3D added support for coinor-bonmin in 
https://github.com/HendrikBrueckler/QGP3D/commit/e218c98463a596cfccec4f2689ef0d781a1f6da7
